@startuml diag
hide empty members

class Carte {
    {field} String question
    {field} String reponse
    {method} String getQuestion()
    {method} String getReponse()
    {method} void setQuestion(String question)
    {method} void setReponse(String reponse)
}

class PaquetDeCartes {
    {field} String titre
    {field} String auteur
    {method} String getTitre()
    {method} ArrayList<Carte> getCartes()
    {method} void setTitre(String titre)
    {method} void setCartes(ArrayList<Carte> cartes)
}



interface Observateur{
    {method} void reagir()
}

class SujetObserve{
    {method} void ajouterObservateur()
    {method} void notifierObservateur()
}

class AccueilControleur{


}

interface Initializable{
    {method} void initialize()
}

PaquetDeCartes "*" -- "*" Carte : contient

SujetObserve <|-- PaquetDeCartes
SujetObserve "1"--"*" Observateur
AccueilControleur ..|> Observateur
AccueilControleur --"1" PaquetDeCartes
AccueilControleur ..|> Initializable


@enduml


